## в каком окружении все будет запускаться
image: node:latest

build:
   stage: build
   cache:
      key: cache-node-modules-${CI_COMMIT_REF_SLUG}
      paths:
         - node_modules
   script:
      - npm i
      - npm run build
   artifacts:
      paths:
         - node_modules/

test:
   stage: test
   script:
      - npm test -- -u
